apiVersion: apps/v1
kind: Deployment
metadata:
    name: addfront
    labels:
       app: add-web
       tier: frontend
spec:
    replicas: 1
    selector:
        matchLabels:
              app: add-web
              tier: frontend
    template:
        metadata:
            labels:
               app: add-web
               tier: frontend
        spec:
           containers:
           - name: addapic
             image: siva3100/addapi:$BUILD_NUMBER
             ports:
             - containerPort: 8080
---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: addback
    labels:
       app: add-web
       tier: backend
spec:
    replicas: 1
    selector:
        matchLabels:
              app: add-web
              tier: backend
    template:
        metadata:
            labels:
               app: add-web
               tier: backend
        spec:
           containers:
           - name: a19ddsvcc
             image: siva3100/addsvc:$BUILD_NUMBER
             ports:
             - containerPort: 3306
---

apiVersion: v1
kind: Service
metadata:
    name: add-web-service
spec:
    selector:
         app: add-web
         tier: frontend
    type: NodePort
    ports:
    - protocol: TCP
      nodePort: 31119
      port: 8080
      targetPort: 8080
---

apiVersion: v1
kind: Service
metadata:
    name: add-back-service
spec:
   selector:
       app: add-web
       tier: backend
   ports:
   - protocol: TCP
     port: 3306
     targetPort: 3306
